apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
  - cluster.yaml
  - pgadmin.yaml
  - cluster-ingress.yaml
  - db-cluster-superuser-secret.yaml
  - psql-owner-password-secret.yaml
  - password-drift-cronjob.yaml
