apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-cloudnative-pg.yaml
  - helmrepo-cloudnative-pg.yaml
  - helmrelease-cloudnative-pg.yaml
  - db-cluster-superuser-secret.yaml
  - psql-owner-password-secret.yaml
  - n8n-db-user-secret.yaml
  - utro-db-user-secret.yaml
  - cluster.yaml
  - cluster-ingress.yaml
  - pgadmin.yaml