apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-secrets-operator
  - flux-system
  - kubernetes-sigs
  - n8n
  - nginx-ingress
  - openebs
  - pg-operator
  - utro
