apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cert-manager
  - external-secrets-operator
  - openebs
  - kubernetes-sigs
  - atlas-operator
  - pg-operator
