apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-policies.yaml
  - image-repositories.yaml
  - image-update-automation.yaml
  - gateway-statefulset.yaml
  - gateway-service.yaml
  - core-statefulset.yaml
  - core-service.yaml
  - ui-statefulset.yaml
  - ui-service.yaml