apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
  - cluster.yaml
  - pgadmin.yaml
  - cluster-ingress.yaml
  - ../../clusters/may-chang/cloudnative-pg/db-cluster-superuser-secret.yaml
  - ../../clusters/may-chang/cloudnative-pg/psql-owner-password-secret.yaml
  - ../../clusters/may-chang/cloudnative-pg/n8n-db-user-secret.yaml
  - ../../clusters/may-chang/cloudnative-pg/utro-db-user-secret.yaml
