apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clustersecretstore-google-secrets.yaml
  - aws-access-key.yaml
  - aws-secret-access-key.yaml
  - letsencrypt-http-private-key.yaml