apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# The Flux Kustomization that applies this directory specifies dependsOn for
# the PostgreSQL cluster and external secrets resources. This base simply lists
# the job manifest.
resources:
  - n8n-configmap.yaml
  - n8n-deployment.yaml
  - n8n-ingress.yaml
  - n8n-service.yaml
