apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-cert-manager.yaml
  - helmrepo-jetstack.yaml
  - helmrelease-cert-manager.yaml
  - clusterissuer-selfsigned.yaml
  - certificate-n8n.yaml
