apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atlas-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
      namespace: flux-system
  interval: 10m
  path: ./clusters/may-chang/atlas-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
