apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-sigs
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/may-chang/kubernetes-sigs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
