apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: utro
  namespace: flux-system
spec:
  dependsOn:
    - name: pg-operator
      namespace: flux-system
    - name: external-secrets-resources
      namespace: flux-system
  interval: 10m
  path: ./clusters/may-chang/utro
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
